name: Deploy
on:
  push:
    branches:
      - "OPB_Homologacao"
  pull_request:
    branches:
      - "main"
jobs:
  deploy:
    env:
      enable-deploy: ${{ github.ref_name == 'OPB_Homologacao' || (github.repository !=  'Sensedia/areadesenvolvedor' && github.ref_name == 'main')}}
    name: Deploy Github pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        if: env.enable-deploy == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
      