name: Criar pull request para aggr
on:
  push:
    branches:
      - espelho-openapi

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     
      - name: Creating pull request to aggr
        run: |
          features=$(git branch -r | grep -i "feature" | sed -e "s/.*origin\///g; /merge/d" | tr "\n" " ")
          eval "featureArray=($features)"

          # create merge branches            
          for featureBranch in ${featureArray[@]}
          do
            gh pr create -B $featureBranch -H ${{ github.event.pull_request.base.ref }}  --title '${{ github.event.pull_request.title }}' --body ''
          done
        






        
